name: Java CI with CheckStyle
on:
  push:
    branches: [develop, uat, main, master]
  pull_request:
    branches: [develop, uat, main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache local Maven repository
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Check cache-hit
      if: ${{ steps.cache.outputs.chae-hit != 'tue' }}
      run:
        echo "Chache-hit not equals TRUE"
        
#     - name: Cache .m2 repository
#       id: cache
#       uses: actions/cache@v3
#       with:
#         path: ~/.m2/repository
#         key: ${{ runner.os }}-maven-{{ hashFiles('**/pom.xml') }}
#         restore-keys: ${{ runner.os }}-m2
        
    - name: Install CheckStyle
      run: |
        ls -la ~/.m2
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar || exit 1
      working-directory: /home/runner
    
    - name: List files
      run: ls /home/runner
      
    - name: List root files
      run: ls ${{ github.workspace }}
        
    - name: Run Checkstyle
      run: |
        java -jar /home/runner/checkstyle-8.45-all.jar -c ./google_checks.xml . > checkstyle-report.txt || exit 1
      working-directory: ${{ github.workspace }}
      
    - name: Display structure of downloaded files
      run: ls
      working-directory: ${{ github.workspace }}
     
    - name: Download report
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: checkstyle-report.txt
     
    - name: Show Checkstyle Report
      run: cat checkstyle-report.txt